name: hybrid_image
description: This package wraps the flutter_svg package and the Flutter SDK image constructors. The package picks the right Image constructor based on extension
version: 0.0.4
homepage: https://github.com/DutchCodingCompany/hybrid_image

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^0.23.0+1
  path: ^1.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
